### ISSUE TITLE
[feat] #42 사전알림 기능 구현

### ISSUE THREAD

**Issue by jwnnoh** [Leets-Official/Leets-BE#42]
## 1. 무엇을?
- 5기 모집을 위한 사전알림 기능을 구현합니다.
<br>

## 2. 상세 설명
메일링을 통한 사전알림 기능을 구현합니다.

<br>

## 3. 추가 사항
꼭 나아연님의 리뷰를 받아야 합니다.

**Comment by ay-eonii** [comment]
웃기네용가리 ㅋㅋ 화이팅 하십쇼
